apiVersion: "v1"
kind: "Service"
metadata:
  name: "ping-demo-service"
  labels:
    app: "ping-demo"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "ping-demo"
  type: "LoadBalancer"